language: generic

#define GITHUB_TOKEN variable at Environment Variables for your progect in Travis

env:
  - |
      MASTER_TARGET_BRANCH=upm #for master
      DEVELOP_TARGET_BRANCH=upm-dev #for develop
      TEST_BRANCH=upm-test #for other branches
      TARGET_BRANCH=not_defined #upm-branch to clone, will be chosen later
      TEST_RUN=false #will be true if branch is not master or develop
      FOLDER_TO_EXPORT=Assets/ParentFolder #parent folder for your root directory

sudo: required

before_install:
  - |
      if [ "$TRAVIS_BRANCH" = "develop" ]; then
        TARGET_BRANCH=$DEVELOP_TARGET_BRANCH
      elif [ "$TRAVIS_BRANCH" = "master" ]; then
        TARGET_BRANCH=$MASTER_TARGET_BRANCH
      else 
        TARGET_BRANCH=$DEVELOP_TARGET_BRANCH #include your test branch in branches section to 
        TEST_RUN=true
      fi 

after_success:
  - chmod 777 -R ci
  - ci/move_to_packagebranch.sh

branches:
  only:
    - master
    - develop
    - /^(?i:test).*$/
  except:
    - /^(?i:upm).*$/